sudo: require

services:
    - docker

before_install:
    - docker build -t docker-image .

script:
    - docker run -m 4g java  -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XshowSettings:vm -version
    - docker run -m 4g docker-image
